[package]
name = "jbob"
version = "0.1.0"
authors = ["Eric Kidd <git@randomhacks.net>"]

[profile.release]
# Use various options to cut down binary size.
debug = false
lto = true
panic = "abort"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
